server:
  port: 8080
  servlet:
    context-path: /warehouse

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/db_warehouse_test"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "+sKONebNUcmUmf+npmjczX4luDnOk4troBnQMmhVxqp64MSKvk5XrVe2Ijr1X+qS"