server:
  port: 8080
  servlet:
    context-path: /warehouse

spring:
  datasource:
#    url: "jdbc:mysql://localhost:3308/dms"
    url: "jdbc:mysql://root:djmKscHRybNghuruePZFgPbdncEMibEv@mysql.railway.internal:3306/railway"
    username: root
#    password: root
    password: djmKscHRybNghuruePZFgPbdncEMibEv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "+sKONebNUcmUmf+npmjczX4luDnOk4troBnQMmhVxqp64MSKvk5XrVe2Ijr1X+qS"